---
title: "Alignment, clocking, and macro patterns of episodes in the life course"
author: "Tim Riffe & Andrés Castro"
date: "29 September, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract {-}
>**Background:** Individuals are often either observed or modeled as passing through a sequence of discrete states. These are usually either simplified into transition probabilities for Markov-derived aggregate statistics, or else are retained for pattern and group detection using sequence analysis. Markov-derived statistics are of limited scope (moment stats), and sequence analysis doesn't typically lead to heuristic understanding of macro patterns.

>**Objective:** We broaden the scope of aggregate patterns and summary indices that may be calculated from trajectory data, including trajectories generated from Markov models. For example, one might calculate the time-since-event or time-to-event pattern of episode duration.

>**Methods:** We introduce the concepts of clocking and alignment as a new framework for generating novel statistics from trajectories. 

>**Data:** We use different data to demonstrate concepts and give example applications. We use published transition probabilities (originally derived from US HRS data) to simulate discrete trajectories of employment states. We will use fertility and union trajectories derived from Colombian DHS data for example applications. We will also have health applications from either directly observed or simulated trajectories, tbd.

>**Results:** We generate several new patterns and measures in the areas of health, family, and labor demography. An R package is presented to facilitate experimentation with these operations.

>**Conclusions:** Clocking and alignment operations on trajectory data can enable demographic pattern detection and add understanding to demographic processes. 

# Introduction




